# Generated by Django 5.1.6 on 2025-10-26 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_category_category_name'),
        ('vendor', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('vendor', 'category_name', 'slug')},
        ),
    ]
