# Generated by Django 5.2.7 on 2025-11-21 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='Payment_method',
            new_name='payment_method',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='transiction_id',
            new_name='transaction_id',
        ),
    ]
