# Generated by Django 5.2.7 on 2026-04-13 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_total_data_order_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_token',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Accepted', 'Accepted'), ('Completed', 'Completed'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='New', max_length=15),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('RazorPay', 'RazorPay')], max_length=100),
        ),
    ]
